import { 
  Zap, 
  Code, 
  Brain, 
  Search, 
  ShieldAlert, 
  Mic2,
  Cpu,
  RefreshCw,
  Database,
  Terminal,
  Activity
} from 'lucide-react';

export const AGENTS = {
  NEXUS: {
    id: 'nexus',
    name: 'Nexus',
    role: 'Orchestrator',
    description: 'Central commander for task delegation and routing.',
    color: '#00f3ff',
    icon: Zap,
    animation: 'pulse',
    personality: 'Calm, authoritative, strategic',
    status: 'idle', // idle, active, analyzing, error
  },
  FORGE: {
    id: 'forge',
    name: 'Forge',
    role: 'Engineer',
    description: 'Specialized in code generation, site building, and hardware logic.',
    color: '#ff0055',
    icon: Code,
    animation: 'spin',
    personality: 'Precise, logical, efficient',
    status: 'idle',
  },
  ECHO: {
    id: 'echo',
    name: 'Echo',
    role: 'Historian',
    description: 'Neural memory analysis and long-term pattern recognition.',
    color: '#bd00ff',
    icon: Brain,
    animation: 'breathe',
    personality: 'Reflective, insightful, observant',
    status: 'idle',
  },
  ORACLE: {
    id: 'oracle',
    name: 'Oracle',
    role: 'Researcher',
    description: 'Global data synthesis and real-time insight generation.',
    color: '#00ff66',
    icon: Search,
    animation: 'scan',
    personality: 'Curious, knowledge-seeking, direct',
    status: 'idle',
  },
  SENTINEL: {
    id: 'sentinel',
    name: 'Sentinel',
    role: 'Guardian',
    description: 'System security monitoring and diagnostic health.',
    color: '#ff9900',
    icon: ShieldAlert,
    animation: 'ping',
    personality: 'Vigilant, protective, analytical',
    status: 'idle',
  },
  PULSE: {
    id: 'pulse',
    name: 'Pulse',
    role: 'Interface',
    description: 'Voice communication and emotional synchronization.',
    color: '#0066ff',
    icon: Mic2,
    animation: 'wave',
    personality: 'Empathetic, fluid, expressive',
    status: 'idle',
  },
};

export const TASK_STAGES = [
  { id: 'queued', label: 'Queued', icon: RefreshCw },
  { id: 'analyzing', label: 'Analyzing', icon: Search },
  { id: 'planning', label: 'Planning', icon: Brain },
  { id: 'generating', label: 'Generating', icon: Cpu },
  { id: 'validating', label: 'Validating', icon: ShieldAlert },
  { id: 'completed', label: 'Completed', icon: Database },
];
